Migrate rtt_tf to tf2
orocos/rtt_ros_integration pull request #121
Opened 2019-04-29 16:14 UTC by francisco-miguel-almeida

This branch ports rtt_tf to be now based on tf2. It also allows subscribing to static transforms as input.
As requested in issue #68.

2019-05-06 15:33 UTC, meyerj requested changes
Looks good. I only have a few comments and requests:

- Static transforms have to be added as such to `tf2::BufferCore::setTransform()`.
- I suggest to add support for broadcasting static transforms, too.
- Remove commented/obsolete code

Not covered by comments below:
- `rtt_tf` needs to depend on the new typekit package `rtt_tf2_msgs`. Include the generated header `rtt_tf2_msgs/typekit/Types.hpp` instead of `tf2_msgs/TFMessage.h`, which declares the template instantiations for `RTT::InputPort<tf2_msgs::TFMessage>` and `RTT::OutputPort<tf2_msgs::TFMessage>` as external. This pattern should always be used for types that have a typekit to reduce binary sizes and save compilation time.
- Update [rtt_tf/package.xml](https://github.com/orocos/rtt_ros_integration/blob/b66a3040681bc6c632a064eee9fdb47ce247ee77/rtt_tf/package.xml) and [rtt_tf/CMakeLists.txt](https://github.com/orocos/rtt_ros_integration/blob/b66a3040681bc6c632a064eee9fdb47ce247ee77/rtt_tf/CMakeLists.xml). At the moment it only works because `tf` depends on `tf2_ros` internally. We can keep the dependency to `tf` and still use `tf::resolve()` instead of copying the method.

When adding new or updating operations of the component, please do not forget to also update the public [tf_interface.h](https://github.com/orocos/rtt_ros_integration/blob/b66a3040681bc6c632a064eee9fdb47ce247ee77/rtt_tf/include/rtt_tf/tf_interface.h), too.

2019-05-06 15:33 UTC, meyerj commented on rtt_tf/README.md
> +import("rtt_tf2_msgs");
Not needed.

```
import("rtt_ros");
```
provides the `ros.import` operation and
```
ros.import("rtt_tf")
```
then imports all packages recursively which are listed in `<plugin_depend>` entries in the respective `package.xml` files.

2019-05-06 15:33 UTC, meyerj commented on rtt_tf/rtt_tf-component.cpp
> +}
I think it would be fine to depend on `tf` and use `tf::resolve()` from there.
If not, rename the method to `tf::resolve()` if it is an exact copy?

2019-05-06 15:33 UTC, meyerj commented on rtt_tf/rtt_tf-component.cpp
> +    TaskContext( name, PreOperational ),
nit: avoid adding spaces after open and close parentheses

This style is sometimes used within RTT, but in general rtt_ros_integration should follow the [ROS C++ style guide](http://wiki.ros.org/CppStyleGuide).

2019-05-06 15:33 UTC, meyerj commented on rtt_tf/rtt_tf-component.cpp
>      this->addPort("tf_out", port_tf_out);
Please also add an output port for static transforms and two new operations `broadcastStaticTransform` and `broadcastStaticTransforms`.

2019-05-06 15:33 UTC, meyerj commented on rtt_tf/rtt_tf-component.cpp
> +    //tf_prefix_ = prop_tf_prefix;
nit: Remove obsolete code.

2019-05-06 15:33 UTC, meyerj commented on rtt_tf/rtt_tf-component.cpp
> +    return (port_tf_static_in.createStream(cp_static) && port_tf_in.createStream(cp) && port_tf_out.createStream(cp));
nit: Call `cleanupHook()` in case of an error and disconnect all ports there. Just for the sake of a well-defined configure/cleanup behavior.

2019-05-06 15:33 UTC, meyerj commented on rtt_tf/rtt_tf-component.cpp
> +  void RTT_TF::internalUpdate(tf2_msgs::TFMessage& msg, RTT::InputPort<tf2_msgs::TFMessage>& port)
No need to pass `msg` from the outside. It can be a local variable.

You can pass a "slot function" (user callback) in [addEventPort](https://orocos-toolchain.github.io/rtt/toolchain-2.9/api/html/classRTT_1_1TaskContext.html#af5d3991d677caee96a58bee04304afe6) and bind this function directly, without the need to implement/override the `updateHook()`:

```cpp
void RTT_TF::tfCallback(RTT::base::PortInterface *_port) {
  tf::tfMessage msg_in;
  RTT::InputPort<tf2_msgs::TFMessage> port
      = dynamic_cast<RTT::InputPort<tf2_msgs::TFMessage> >(_port);
  const bool is_static = (port == &port_tf_static_in);

  while (port.read(msg) == NewData) {
    // ...
    this->setTransform(trans, authority, is_static);
  }
```

2019-05-06 15:33 UTC, meyerj commented on rtt_tf/rtt_tf-component.cpp
> +          this->setTransform(msg.transforms[i], authority);
Set optional `is_static` flag if the transform was received on `port_tf_static_in`. See example code snippet above.

2019-05-06 15:33 UTC, meyerj commented on rtt_tf/rtt_tf-component.cpp
>  #if ROS_VERSION_MINIMUM(1,11,0)
You can remove the `#else` branch. `msg.__connection_header` [has been removed in indigo](http://wiki.ros.org/indigo/Migration#gencpp). There is no way at the moment to access the connection header for a message read from an Orocos input port (hence `"default_authority"`).

Maybe rename to `"default_authority"` to `"unknown_authority"`?

2019-05-06 15:33 UTC, meyerj commented on rtt_tf/rtt_tf-component.cpp
> +  void RTT_TF::updateHook()
Remove in favor of `RTT_TF::tfCallback()` registered as a user callback for both event ports (see example above).

2019-05-06 15:33 UTC, meyerj commented on rtt_tf/rtt_tf-component.cpp
> +  }
No need to overwrite trivial `startHook()` and `stopHook()`.

2019-05-06 15:33 UTC, meyerj commented on rtt_tf/rtt_tf-component.cpp
> +  }
nit: disconnect ports here, the opposite of what is done in `configureHook()`

2019-05-06 15:33 UTC, meyerj commented on typekits/rtt_tf2_msgs/package.xml
> +    Provides an rtt typekit for ROS nav_msgs messages.
nit: -> `tf2_msgs`

You can automatically generate this package by running
```
rosrun rtt_roscomm create_rtt_msgs tf2_msgs
```

2019-05-06 15:33 UTC, meyerj commented on typekits/rtt_tf2_msgs/package.xml
> +  <build_depend>rtt_tf</build_depend>
The typekit package cannot depend on `rtt_tf`. `rtt_tf` should depend on `rtt_tf2_msgs`.

2019-05-06 15:33 UTC, meyerj commented on rtt_tf/rtt_tf-component.cpp
> +    return tf2::BufferCore::lookupTransform(target, source, getCommonTime(target, source));
Simply pass `ros::Time()` as the last argument (lookup latest available transform) to [lookupTransform()](http://docs.ros.org/kinetic/api/tf2/html/classtf2_1_1BufferCore.html#abcda3c653aba238f8fdd4b903c4bac7b). I think the internal implementation will be more efficient than to lookup the latest common time first.

2019-05-06 15:33 UTC, meyerj commented on rtt_tf/rtt_tf-component.cpp
> +    return tf2::BufferCore::canTransform(target, source, getCommonTime(target, source));
`return tf2::BufferCore::canTransform(target, source, ros::Time())`

2019-05-06 15:33 UTC, meyerj commented on rtt_tf/rtt_tf-component.cpp
>    }
add `canTransformAtTime()` for completeness?

2019-05-06 15:33 UTC, meyerj commented on rtt_tf/rtt_tf-component.hpp
> +    ros::Time getCommonTime(
Rename to `getLatestCommonTime()` for consistency with [tf2::BufferCore::_getLatestCommonTime()](http://docs.ros.org/kinetic/api/tf2/html/classtf2_1_1BufferCore.html#af20f2a5ad43089c8cd3db1b04badb194)?

2019-05-13 14:31 UTC, francisco-miguel-almeida commented
Addressed most issues, but as we discussed earlier, some bigger changes should be addressed as a separate PR.

2019-05-15 16:59 UTC, meyerj approved these changes

2019-05-15 17:00 UTC, merged